name: presse_independante
description: Compilation de plusieurs journaux indépendants

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  meta: ^1.4.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^5.0.0
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0
  stacked: ^2.2.5
  stacked_services:
  get_it:
  injectable:
  auto_route: ^2.3.2
  webview_flutter:
  scrollable_positioned_list:
  url_launcher:
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:
  flutter_launcher_icons:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  apative_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/error.png
  fonts:
    - family: "Libre Bodoni"
      fonts:
        - asset: assets/fonts/LibreBodoni/LibreBodoni-Regular.ttf
          weight: 400
        - asset: assets/fonts/LibreBodoni/LibreBodoni-Bold.ttf
          weight: 700
        - asset: assets/fonts/LibreBodoni/LibreBodoni-BoldItalic.ttf
          style: italic
          weight: 700