name: presse_independante
description: Compilation de plusieurs journaux indépendants

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  provider: ^4.0.4
  build_runner: ^1.10.11
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  stacked:
  stacked_services:
  get_it:
  injectable:
  auto_route:
  webview_flutter:
  scrollable_positioned_list:
  url_launcher:
  cached_network_image:

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:
  flutter_launcher_icons:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  apative_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/error.png
  fonts:
    - family: "Libre Bodoni"
      fonts:
        - asset: assets/fonts/LibreBodoni/LibreBodoni-Regular.ttf
          weight: 400
        - asset: assets/fonts/LibreBodoni/LibreBodoni-Bold.ttf
          weight: 700
        - asset: assets/fonts/LibreBodoni/LibreBodoni-BoldItalic.ttf
          style: italic
          weight: 700